# Generated by Django 4.2.3 on 2023-08-19 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notetask", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="deadline",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[
                    ("Not Start Yet", "Not Start Yet"),
                    ("Doing", "Doing"),
                    ("Finish", "Finish"),
                ],
                default="Not Start Yet",
                max_length=20,
            ),
        ),
    ]
