# Generated by Django 3.2.14 on 2023-07-28 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginn', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Input',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200)),
                ('A', models.CharField(max_length=50)),
                ('B', models.CharField(max_length=50)),
                ('C', models.CharField(max_length=50)),
                ('D', models.CharField(max_length=50)),
                ('answer', models.CharField(max_length=50)),
            ],
        ),
    ]
